# Generated by Django 3.0.3 on 2021-05-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210515_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
