# Generated by Django 3.0.3 on 2021-05-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210515_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='qualifications',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
