# Generated by Django 3.2.4 on 2021-06-05 09:50

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_qual_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='answer_to_questions_if_any',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default=None, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='post',
            name='email_ID',
            field=models.EmailField(default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='resume',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
    ]
