# Generated by Django 3.2.4 on 2021-06-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20210605_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='answer_to_questions_if_any_html',
            field=models.TextField(blank=True, default='', editable=False, null=True),
        ),
    ]
