# Generated by Django 3.2.4 on 2021-06-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_answer_to_questions_if_any_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='resume',
            field=models.FileField(blank=True, default=None, null=True, upload_to='resumes/'),
        ),
    ]
