# Generated by Django 3.1.2 on 2021-06-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_post_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='accepted',
            field=models.CharField(default='No', max_length=255, null=True),
        ),
    ]
