# Generated by Django 3.1.2 on 2021-06-08 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_post_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='accepted',
        ),
    ]
