# Generated by Django 3.2.1 on 2021-06-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_remove_post_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='accepted',
            field=models.CharField(choices=[('nd', 'Not Decided'), ('r', 'Rejected'), ('a', 'Accepted')], default='nd', max_length=255),
        ),
    ]
