# Generated by Django 3.1.2 on 2021-06-02 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210527_0243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='job1',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='job2',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='job3',
        ),
    ]
