# Generated by Django 3.1.4 on 2021-05-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20210503_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='cpi_cutoff',
        ),
        migrations.AddField(
            model_name='group',
            name='field_of_job',
            field=models.CharField(choices=[('ml', 'ML'), ('appd', 'APPD'), ('webdf', 'WEBDF'), ('webdb', 'WEBDB'), ('sde', 'SDE')], default='sde', max_length=255),
        ),
        migrations.AddField(
            model_name='group',
            name='skills_required',
            field=models.CharField(choices=[('react', 'REACT'), ('python', 'PYTHON'), ('java', 'JAVA'), ('django', 'DJANGO'), ('js', 'JS')], default='sde', max_length=255),
        ),
    ]
