# Generated by Django 3.1.4 on 2021-05-06 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0003_auto_20210503_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='creator',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='group_creator', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='skills_required',
            field=models.CharField(choices=[('react', 'REACT'), ('python', 'PYTHON'), ('java', 'JAVA'), ('django', 'DJANGO'), ('js', 'JS')], default='js', max_length=255),
        ),
    ]
