# Generated by Django 3.0.3 on 2021-05-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_auto_20210506_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='duration',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='expected_qualifications',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='stipend',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
