# Generated by Django 3.0.3 on 2021-05-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_auto_20210515_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='apply_by',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='start_date',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
