# Generated by Django 3.1.4 on 2021-05-26 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_auto_20210527_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='selected_count',
            field=models.IntegerField(default=0),
        ),
    ]
