# Generated by Django 3.2.4 on 2021-06-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_group_selected_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='selected1',
        ),
        migrations.RemoveField(
            model_name='group',
            name='selected2',
        ),
        migrations.RemoveField(
            model_name='group',
            name='selected3',
        ),
        migrations.RemoveField(
            model_name='group',
            name='selected_count',
        ),
        migrations.RemoveField(
            model_name='group',
            name='skills_required',
        ),
        migrations.AddField(
            model_name='group',
            name='additional_questions_to_applicant',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='duration',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='stipend',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
