# Generated by Django 3.2.4 on 2021-06-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0009_auto_20210605_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='vacancy',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
