# Generated by Django 3.2.4 on 2021-06-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0010_group_vacancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='vacancy',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
