# Generated by Django 3.1.4 on 2021-06-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0012_group_workstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='branch',
            field=models.CharField(choices=[('bt', 'Biotech'), ('ch', 'Chemical'), ('cse', 'Computer Science'), ('mnc', 'Mathematics'), ('ep', 'Engineering Physics'), ('ece', 'Electronics'), ('ee', 'Electrical'), ('me', 'Mechanical'), ('cv', 'Civil'), ('cst', 'CST'), ('na', 'Not Applicable')], default='na', max_length=255),
        ),
        migrations.AddField(
            model_name='group',
            name='btp',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
