# Generated by Django 3.1.4 on 2021-06-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0013_auto_20210607_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='finished',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
