# Generated by Django 3.1.2 on 2021-06-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0014_group_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
