# Generated by Django 3.2.1 on 2021-06-26 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0015_group_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='accepted',
        ),
    ]
